---

   - name: Install aptitude using apt
     apt:
       name: aptitude
       state: latest
       update_cache: yes
       force_apt_get: yes

   - name: Install required system packages
     apt:
       name: "{{ item }}"
       state: latest
       update_cache: yes
     loop:
       - apt-transport-https
       - ca-certificates
       - curl
       - gnupg-agent
       - software-properties-common

   - name: Add Docker GPG apt Key
     apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

   - name: Add Docker Repository
     apt_repository:
       repo: deb https://download.docker.com/linux/ubuntu bionic stable
       state: present

   - name: Update apt and install docker-ce
     apt:
       update_cache: yes

   - name: Install required system packages
     apt:
       name: "{{ item }}"
       state: latest
       update_cache: yes
     loop:
         - docker-ce
         - docker-ce-cli
         - containerd.io

   - name: Run whoami without become.
     command: whoami
     changed_when: false
     become: false
     register: whoami

   - name: add user to group docker
     user:
         name: "{{ item }}"
         groups: docker
         append: yes
     loop:
       - "{{ whoami.stdout }}"
       - jenkins
